### ISSUE TITLE
ModuleNotFoundError: No module named 'microrepl'

### ISSUE THREAD

**Issue by hickford** [ntoll/microrepl#12]
Hi. I just installed microrepl `pip install microrepl` but when I try to run the microrepl command I get an error

> ModuleNotFoundError: No module named 'microrepl'

Any ideas?

**Comment by hickford** [comment]
If it helps, here's a log

```
>pip install microrepl
Collecting microrepl
  Using cached microrepl-0.5.tar.gz
Requirement already satisfied: pyserial in c:\python36\lib\site-packages (from microrepl)
Building wheels for collected packages: microrepl
  Running setup.py bdist_wheel for microrepl ... done
  Stored in directory: C:\Users\hats\AppData\Local\pip\Cache\wheels\da\75\6e\a8fb412310960faa2fe77ce5687e6c313c8773ccd01910d1c1
Successfully built microrepl
Installing collected packages: microrepl
Successfully installed microrepl-0.5

>microrepl
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\microrepl.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'microrepl'
```

Using Python 3.6 on Windows


    C:\Users\hats>python
    Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by amoibos** [comment]
Pip installation is broken, download, unpack and install("python setup.py install") manually.
